#!/usr/bin/env ruby
Dir['./helpers/*.rb'].each {|file| require file }
Dir['./models/*.rb'].each {|file| require file }
Dir['./views/*.rb'].each {|file| require file }
require 'date'

c = Controller.new
c.run(ARGV[0])